---
title: "R Notebook - putamen subtype clustering"
output:
  pdf_document: default
  # html_notebook: default
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "../")
# knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.retina = T)
```

```{r echo=FALSE, message=FALSE}
library(Seurat)
library(hash)
library(magrittr)
library(dplyr)
library(tidyr)
library(stringi)
library(gplots)
library(flashClust)
library(ape)
library(purrr)
library(cowplot)
library(tibble)
library(ggplot2)
library(scales)
library(lattice)

set.seed(12345)
```


```{r}
putamen_microglia <- readRDS("../data/clustered_data/putamen_microglia.rds")
Idents(putamen_microglia) <- "cell_type"
putamen_microglia <- subset(putamen_microglia, cell_type != "Exclude")
```


```{r}
DimPlot(putamen_microglia, group.by = "cell_type",
        split.by = "stim", ncol = 1,
        pt.size = 0.8, label = F, repel = T,
        label.size = 4, reduction = "tsne") +
  facet_wrap(~stim, strip.position = "left", ncol = 1) +
  guides(color=guide_legend(ncol=1, override.aes = list(size=4))) +
  theme( axis.line=element_blank(),
         strip.text = element_text(size = rel(1.2)),
         axis.text.x=element_blank(),
         axis.text.y=element_blank(),
         axis.ticks=element_blank(),
         axis.title.x=element_blank(),
         axis.title.y=element_blank(),
         legend.text=element_text(size=rel(1.1)),
         legend.position = "left",
         plot.title = element_blank(),
         panel.background=element_blank(),
         panel.border=element_blank(),
         panel.grid.major=element_blank(),
         panel.grid.minor=element_blank(),
         plot.background=element_blank())
```

```{r warning=F, message=F}
Idents(putamen_microglia) <- "cell_type"

marker.genes <- c("CSF1R", "P2RY12", "CX3CR1", "TYROBP", "CD74",
                  "MRC1", "TLR4",
                  "CD2", "IL7R", "S100A4")

VlnPlot(subset(putamen_microglia, stim == "Control"),
        fill.by = "ident",
        features = marker.genes, stack = T,
        flip = T, assay = "RNA") +
  theme(axis.title.x = element_blank()) +
  NoLegend()
```


```{r message=F}
dam1_down_markers <- c("CX3CR1", "P2RY12", "TMEM119")
dam1_up_markers <- c("TYROBP", "APOE", "B2M", "TIMP2", "CSTB")
dam2_up_markers <- c("TREM2", "ITGAX", "AXL", "CLEC7A", "CSF1R")

dam_markers <- c(dam1_down_markers, dam1_up_markers, dam2_up_markers)

DotPlot(putamen_microglia,
        idents = c("MG1", "MG2"),
        group.by = "stim", assay = "RNA",
        features = dam_markers, scale = F, dot.min = 0
               ) +
    coord_flip() +
    scale_radius(range = c(0, 8), limits = c(0, 100)) +
    guides(color = guide_colorbar(title = "Scaled Avg Expression")) +
    guides(size = guide_legend(title = "Percent Expressed")) +
    theme(
        axis.text.x = element_text(face = "bold", angle = 90, vjust = 0.5),
        axis.text.y = element_text(size = rel(1.2), face = "bold", angle = 0),
        axis.line=element_blank(),
        axis.ticks=element_blank(),
        axis.title.y = element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        axis.title.x = element_blank())
```


```{r}
interim.plot <- DotPlot(putamen_microglia,
                        features = dam_markers,
                        idents = c("MG1", "MG2"),
                        group.by = "stim",
                        split.by = "cell_type",
                        assay = "RNA", scale = T,
                        cols = rep("blue", 4)
                        )
data.plot <- as.data.frame(interim.plot["data"])

data.plot <- data.plot %>%
  separate(data.id, c("data.stim","data.celltype"), sep = "_")

ggplot(data.plot, mapping = aes(x = data.stim, y = data.features.plot)) +
  geom_point(mapping = aes(size = data.pct.exp,
                                  color = rescale(data.avg.exp.scaled, to = c(-1,1)) )) +
  facet_grid(~ data.celltype) +
  scale_radius(range = c(0, 7), limits = c(0, 100)) +
  scale_color_gradient(low = "lightgrey", high = "blue") +
  scale_x_discrete(position = "bottom") +
  
  guides(size = guide_legend(title = "Percent Expressed")) +
  guides(color = guide_colorbar(title = "Scaled Average Expression")) +
  
  theme_cowplot() +
  # ggtitle("", subtitle = paste("Expression", sep = " ")
  #         ) +
  
  theme(axis.text.x = element_text(face = "bold", angle = 45, hjust = 0.5),
        axis.text.y = element_text(size = rel(1.2), face = "bold", angle = 0),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        plot.background = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_blank(),
        plot.subtitle = element_text(size = rel(1.5), face = "bold"))
```
