---
title: "R Notebook - putamen subtype clustering"
output:
  pdf_document: default
  # html_notebook: default
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "../")
# knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.retina = T)
```

```{r echo=FALSE, message=FALSE}
library(Seurat)
library(hash)
library(magrittr)
library(dplyr)
library(tidyr)
library(stringi)
library(gplots)
library(flashClust)
library(ape)
library(purrr)
library(cowplot)
library(tibble)
library(ggplot2)
library(scales)
library(lattice)


set.seed(12345)
```


```{r}
data_celltypes <- readRDS("../data/overall_clustered_data/data_celltypes_annotated.rds")
```


Filter Neurons from annotated cells
```{r}
data_neurons <- subset(data_celltypes, idents = "Neuron")

print(as.data.frame(
  table(data_neurons$stim, dnn=list("Group")),
  responseName = c("Count")
  )
)
```

```{r}
DimPlot(data_neurons, reduction = "tsne", group.by = "stim")
DimPlot(data_neurons, label = T, reduction = "tsne", group.by = "seurat_clusters")
```


Split and Integrate CTRL, PD and MSA data

```{r echo=FALSE, message=FALSE}

putamen.list <- SplitObject(data_neurons, split.by = "orig.ident")

normAndVarFeatures <- function(seuratObj){
  DefaultAssay(seuratObj) <- "RNA"
  seuratObj <- NormalizeData(seuratObj, verbose=FALSE)
  seuratObj <- FindVariableFeatures(seuratObj, selection.method="vst", nfeatures = 1000, verbose=FALSE)
  return(seuratObj)
}

putamen.list <- lapply(putamen.list, normAndVarFeatures)

k.filter <- min(200, min(sapply(putamen.list, ncol)))

combined.anchors <- FindIntegrationAnchors(
  object.list = putamen.list,
  anchor.features = 1000,
  k.filter = k.filter
)

combined.integrated <- IntegrateData(anchorset = combined.anchors)

```


Dimensionality Reduction
```{r}
cat("combined data default assay: ", DefaultAssay(combined.integrated))
combined.integrated <- ScaleData(combined.integrated, verbose=FALSE)
combined.integrated <- RunPCA(combined.integrated, verbose=TRUE)

combined.integrated
```

Determine number of PC to use for downstream analysis
```{r}
ElbowPlot(combined.integrated, ndims = 40)
```


```{r echo=FALSE}
combined <- FindNeighbors(combined.integrated, dims = 1:12)

combined <- RunUMAP(combined, dims = 1:12)
combined <- RunTSNE(combined, dims = 1:12)
#Clustering and visualization(using tSNE and UMAP); resolution can vary
```

```{r echo=FALSE}
# vary clustering parameter
DefaultAssay(combined) <- "integrated"
combined <- FindClusters(combined, resolution = 0.1)
```

```{r}
DimPlot(combined, reduction = "umap", group.by = "orig.ident")
DimPlot(combined, reduction = "umap", label = T, group.by = "seurat_clusters")
DimPlot(combined, reduction = "umap", split.by = "orig.ident", ncol = 3)
DimPlot(combined, reduction = "umap", split.by = "stim", ncol = 3)
```

```{r}
DimPlot(combined, reduction = "tsne", group.by = "orig.ident")
DimPlot(combined, reduction = "tsne", group.by = "seurat_clusters")
DimPlot(combined, reduction = "tsne", split.by = "orig.ident", ncol = 3)
DimPlot(combined, reduction = "tsne", split.by = "stim", ncol = 3)
```


```{r}
DefaultAssay(combined) <- "RNA"
combined <- ScaleData(combined, verbose = FALSE)
```


```{r}
DefaultAssay(combined) <- "RNA"
plot.list <- FeaturePlot(combined, reduction = "tsne",
                         features = c("PPP1R1B", "DRD1",
                                      "GAD1" , "DRD2"),
                         label = T, keep.scale = "all",
                         ncol = 2, combine = F)

patchwork::wrap_plots(lapply(plot.list, function(p){
  return(p + theme(axis.title = element_blank(),
                   axis.ticks = element_blank(),
                   axis.line = element_blank(),
                   axis.text = element_blank()) + NoLegend())
}))
```

```{r message=FALSE, echo=FALSE, warning=FALSE}
all.markers <- FindAllMarkers(subset(subset(combined, stim == "Control"), idents = c(0,1,3,4,5,6) ),
                        logfc.threshold = 0.25, only.pos = F,
                        test.use = "MAST", min.pct = 0.1,
                        assay = "RNA", verbose = F)

write.csv(all.markers, "../data/deg/neurons/control/neurons.cluster.markers.csv", row.names = F)
```


```{r}
table(combined$stim, combined$seurat_clusters)
table(combined$stim, combined$cell_type)
```


```{R}
VlnPlot(combined,
        features = c("nFeature_RNA", "percent.mt"),
        assay = "RNA", pt.size = 0)
```


```{r message=F, warning=F}
# check <- FindAllMarkers(subset(combined, idents = c(0,1,3,4)), test.use = "MAST")
marker.genes <- c( "RBFOX3", "SLC17A7",
                   "PPP1R1B", "NRGN", "GAD1", "GAD2",
                   "DRD1", "DRD2",
                   # "LUZP2",
                   "ADARB2",
                   # "SOX6",
                   "LHX6", "NXPH1",
                   "NELL1", "FGFR2",
                   "CUX2", "KCNC2"
                   # "SEMA5A",
                   # "LINGO2",
                   # "BCAS1", "OPALIN", "HAPLN2",
                   )

# VlnPlot(subset(subset(combined, stim == "Control"), idents = c(0,1,3,4,5,6)),
#         features = marker.genes,
#         group.by = "seurat_clusters",
#         assay = "RNA", fill.by = "ident",
#         stack = T, flip = T) + NoLegend()

VlnPlot(subset(subset(combined, stim == "Control"), cell_type != "Exclude"),
        features = marker.genes,
        group.by = "cell_type",
        assay = "RNA", fill.by = "ident",
        stack = T, flip = T) + NoLegend()
```


```{r}
new.cell.types <- c("D1MSN",       #- Cluster 0
                    "D2MSN",       #- Cluster 1
                    "Exclude",     #- Cluster 2
                    "D2MSN",       #- Cluster 3
                    "MSN",     #- Cluster 4
                    "GABA1",       #- Cluster 5
                    "GABA2",       #- Cluster 6
                    "Exclude",     #- Cluster 7
                    "Exclude",     #- Cluster 8
                    "Exclude"      #- Cluster 9
                    )

Idents(combined) <- "seurat_clusters"

names(new.cell.types) <- levels(combined)

combined <- RenameIdents(combined, new.cell.types)
combined$cell_type <- Idents(combined)

Idents(combined) <- "cell_type"
```


Differential Gene Expression

```{r}
for(cluster in c("D1MSN", "D2MSN", "MSN", "GABA1", "GABA2") ){
  inter <- subset(combined, idents = cluster)
  Idents(inter) <- "stim"
  
  for(condition in c("MSA", "PD")){
    de_genes <- FindMarkers(inter, ident.1 = condition, ident.2 = "Control",
                     assay = "RNA", only.pos = F, min.pct = 0.1, verbose = 5)
    write.csv(de_genes, paste0("../data/deg/neurons/stim/cluster_",
                                    cluster, "_",
                                    condition, "_vs_Control", ".csv")
              )
  }
}
```


```{r}
saveRDS(combined, "../data/clustered_data/putamen_neurons.rds")
# combined <- readRDS("../data/clustered_data/putamen_neurons.rds")
```


```{r}
cell.idents <- data.frame(cluster_id = combined$seurat_clusters,
                          sample_id = combined$orig.ident,
                          group_id = combined$stim,
                          cluster_type = Idents(combined)
                          )

cell.agg <- cell.idents %>%
  group_by(group_id, sample_id) %>%
  mutate(sample_size = length(sample_id)) %>%
  group_by(group_id, sample_id, cluster_type) %>%
  mutate(cluster_size = length(cluster_type)) %>%
  mutate(cluster_proportion = cluster_size/sample_size) %>%
  distinct()

bwplot(cluster_proportion ~ group_id|cluster_type, cell.agg,
       layout=c(4,1), scale = list(x=list(rot=60)))

bwplot(cluster_proportion ~ cluster_type|group_id, cell.agg,
       layout=c(3,1), scale = list(x=list(rot=60)))


dotplot(cluster_proportion ~ group_id|cluster_type, cell.agg,
       layout=c(4,1), scale = list(x=list(rot=60)))

bwplot(paste(cluster_type, group_id, sep = "  ---   ") ~ cluster_proportion, cell.agg)

```





